export const data = [
	{
	  id: 1,
	  img: require('./components/Imagenes/PerfectMe.png'), 
	  nombreProducto: 'PerfectMe',
	  precio: 75,	
	  categoria: 'Rostro',
	},
	{
	  id: 2,
	  img: require('./components/Imagenes/killcover.png'), 
	  nombreProducto: 'Killcover',
	  precio: 60,
	  categoria: 'Rostro',	
	},
	{
	  id: 3,
	  img: require('./components/Imagenes/Glasting cherry.jpg'), 
	  nombreProducto: 'Glasting cherry',
	  precio: 70,
	  categoria: 'Labios',	
	},
	{
	  id: 4,
	  img: require('./components/Imagenes/Fashion water.jpg'), 
	  nombreProducto: 'Fashion water',
	  precio: 80,
	  categoria: 'Labios',	
	},
	{
		id: 5,
		img: require('./components/Imagenes/Rose ring.png'), 
		nombreProducto: 'Rose ring',
		precio: 80,
		categoria: 'Accesorios',	
	},
	{
		id: 6,
		img: require('./components/Imagenes/snake ring.png'), 
		nombreProducto: 'Snake ring',
		precio: 100,
		categoria: 'Accesorios',	
	},
	{
		id: 7,
		img: require('./components/Imagenes/Mariposita.png'), 
		nombreProducto: 'Mariposita',
		precio: 100,
		categoria: 'Accesorios',	
	},
	{
		id: 8,
		img: require('./components/Imagenes/Florecitas.png'), 
		nombreProducto: 'Florecitas',
		precio: 100,
		categoria: 'Accesorios',	
	},
	{
		id: 9,
		img: require('./components/Imagenes/Maripositas.png'), 
		nombreProducto: 'Maripositas',
		precio: 80,
		categoria: 'Accesorios',	
	},
	{
		id: 10,
		img: require('./components/Imagenes/Rositas.png'), 
		nombreProducto: 'Rositas',
		precio: 80,
		categoria: 'Accesorios',	
	},
	{
		id: 11,
		img: require('./components/Imagenes/Gloss fruit.png'), 
		nombreProducto: 'Gloss fruit',
		precio: 70,
		categoria: 'Labios',	
	},
	{
		id: 12,
		img: require('./components/Imagenes/Matte blur.png'), 
		nombreProducto: 'Matte blur',
		precio: 70,
		categoria: 'Labios',	
	},
	{
		id: 13,
		img: require('./components/Imagenes/Velvet deluxe.jpg'), 
		nombreProducto: 'Velvet deluxe',
		precio: 70,
		categoria: 'Labios',	
	},
	{
		id: 14,
		img: require('./components/Imagenes/Zero matte.jpg'), 
		nombreProducto: 'Zero matte',
		precio: 70,
		categoria: 'Labios',	
	},
	{
		id: 15,
		img: require('./components/Imagenes/Crayon liner.png'), 
		nombreProducto: 'Crayon liner',
		precio: 50,
		categoria: 'Ojos',	
	},
	{
		id: 16,
		img: require('./components/Imagenes/Waterproof line.png'), 
		nombreProducto: 'Waterproof line',
		precio: 60,
		categoria: 'Ojos',	
	},
	{
		id: 17,
		img: require('./components/Imagenes/All stay.jpg'), 
		nombreProducto: 'Waterproof line',
		precio: 60,
		categoria: 'Ojos',	
	},
	{
		id: 18,
		img: require('./components/Imagenes/Eyelash serum.png'), 
		nombreProducto: 'Eyelash serum',
		precio: 70,
		categoria: 'Ojos',	
	},
	{
		id: 19,
		img: require('./components/Imagenes/Berry palette.jpg'), 
		nombreProducto: 'Berry palette',
		precio: 100,
		categoria: 'Ojos',	
	},
	{
		id: 20,
		img: require('./components/Imagenes/Pink chocolate.jpg'), 
		nombreProducto: 'Pink chocolate',
		precio: 100,
		categoria: 'Ojos',	
	},
	{
		id: 21,
		img: require('./components/Imagenes/Shiny Fu Xuan.jpg'), 
		nombreProducto: 'Shiny Fu Xuan',
		precio: 150,
		categoria: 'Ojos',	
	},
	{
		id: 22,
		img: require('./components/Imagenes/CoverMe.png'), 
		nombreProducto: 'Cover me',
		precio: 100,
		categoria: 'Rostro',	
	},
	{
		id: 23,
		img: require('./components/Imagenes/Waterlike cover.png'), 
		nombreProducto: 'Water like cover',
		precio: 80,
		categoria: 'Rostro',	
	},
	{
		id: 24,
		img: require('./components/Imagenes/FitMe.png'), 
		nombreProducto: 'Fit me',
		precio: 90,
		categoria: 'Rostro',	
	},
	{
		id: 25,
		img: require('./components/Imagenes/FitMe.png'), 
		nombreProducto: 'Fit me',
		precio: 90,
		categoria: 'Rostro',	
	},







  ];