# Generated by Django 3.2.8 on 2023-11-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0002_delete_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('contraseña', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'cuenta',
                'managed': False,
            },
        ),
    ]
