# Generated by Django 3.2.8 on 2023-11-25 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categorias',
        ),
    ]
