# Generated by Django 3.2.8 on 2023-11-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_categorias_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colecciones',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'colecciones',
                'managed': False,
            },
        ),
    ]
