# Generated by Django 5.0.3 on 2024-04-05 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('IDCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCategoria', models.CharField(max_length=100)),
                ('DescripcionCategoria', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('IDUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('NombreUsuario', models.CharField(max_length=100)),
                ('CorreoElectronico', models.CharField(max_length=100)),
                ('Contrasena', models.CharField(max_length=100)),
                ('DireccionEnvio', models.CharField(max_length=255)),
                ('InformacionPago', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('IDProducto', models.AutoField(primary_key=True, serialize=False)),
                ('NombreProducto', models.CharField(max_length=100)),
                ('Descripcion', models.TextField()),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IDCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('IDPedido', models.AutoField(primary_key=True, serialize=False)),
                ('FechaPedido', models.DateField()),
                ('EstadoPedido', models.CharField(max_length=50)),
                ('TotalPedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IDUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
    ]
