# Generated by Django 5.0.4 on 2024-04-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='DireccionEnvio',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='InformacionPago',
        ),
    ]
