# Generated by Django 5.0.4 on 2024-04-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuarios_direccionenvio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='IDUsuario',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
