# Generated by Django 5.0.4 on 2024-04-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuarios_idusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='IDUsuario',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
