# Generated by Django 5.0.4 on 2024-04-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuarios_idusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='IDProducto',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
